### ISSUE TITLE
coordinate value normalization before concatenation with latent code z

### ISSUE THREAD

**Issue by Torment123** [hubert0527/COCO-GAN#14]
Hi, I'm studying the code of your COCO GAN paper, and have a small problem which I hope you can help me with: in the appendix of the paper, it says that inorder to make c' and c'' have similar scale with the latent code, their values are normalized to [-1,1]. But based on my understanding, in the _euclidean_sample_coord function of coord_handler.py, the returned d_macro_coord are within [-1,1], but the g_micro_coord are original pixel positions (because their computation in line 131, 132 all multiplied the gpc_x,gpc_y, which scaled them to original image scale, and I didn't see any other normalization step before it is concatenated with the latent code in the generator, could you help me point out where I got it wrong? Thanks

**Comment by hubert0527** [comment]
Hi @Torment123 ,

Thanks for the question!
Before the line 131 and 132, the values of `g_micro_pos_x_proto` and `g_micro_pos_y_proto` were already in the range `[-1, 1]`.
In line 131 and 132, we first switch the value range from `[-1, 1]` to `[0, 1]` by `(g_micro_pos_x_proto[:,idx] + 1)/2`, then at the end of the line, we switch the value range form `[0, 1]` to `[-1, 1]` again with  `* 2 - 1`.
The computation in the middle (related to the `gpc_x` and `gpc_y`) further casts the `[0, 1]` normalized coordinate values to the raw pixel coordinates, which _was_ written for the purpose of debugging as the raw pixel coordinates are more readable.

Best regard,
Hubert

**Comment by Torment123** [comment]
thanks for the prompt and detailed response, this is helpful
