### ISSUE TITLE
How many epochs for bedroom?

### ISSUE THREAD

**Issue by yifanjiang19** [hubert0527/COCO-GAN#15]
How many epochs for LSUN bedroom dataset to get reported FID? Thanks!

**Comment by hubert0527** [comment]
I believe it should be 3,000,000 iterations with a batch size of 128 (should be roughly equivalent to 128 epochs).
The FID converges extremely slow after 1 million iterations, and still slowly improves over time.
I believe one can obtain a similar score of around 2 million iterations as well.
