### ISSUE TITLE
sample script for sampling from trained models

### ISSUE THREAD

**Issue by dribnet** [hubert0527/COCO-GAN#3]
Hello- would it be possible to provide a sample script or perhaps some guidance on how one would sample from one of the pre-trained models?

**Comment by hubert0527** [comment]
The simplest way is to simply run the training script, and the full images will be shown on the Tensorboard logs. I have never seen our model mode-collapses, so basically you can train it forever.

Another programmatic way is to get it by calling `trainer.rand_sample_full_test()`. It returns a batch of images as a numpy array.
