### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by mcbuehler** [hubert0527/COCO-GAN#7]
How long did you train your models and on what hardware?
I am training on the CelebA dataset, size 64x64 and config N2M2S32. With batch size 64, it takes a bit less than 24h for 50 epochs on a TITAN Xp.

**Comment by hubert0527** [comment]
It also slightly depends on your other hardware equipments, such as hard drive (data loading) and CPU (data loading, preprocessing, FID calculation).

It takes 3 days to yield good results for 64x64 CelebA. But for best FID, it involves lots of randomness. It can take a week or more. In general, the FID will keep dropping if you keep training it.
